### ISSUE TITLE
Latest DrawFBP version missing on Maven Central

### ISSUE THREAD

**Issue by ERnsTL** [jpaulm/drawfbp#17]
Greetings, in the README, it is mentioned that the latest version is (as of 2018-08-09) the version 2.14.1 and that a compiled release version .jar would be available on Maven Central.

Following the given link and searching for *DrawFBP* shows only 2.13.x as the latest version, see [this direct link](https://search.maven.org/search?q=a:drawfbp)  - the 2.14.x versions are missing.

**Comment by jpaulm** [comment]
V2.14.2 now on Maven.  Thanks, @ERnsTL
