### ISSUE TITLE
External Ports not generating correct symbols

### ISSUE THREAD

**Issue by jpaulm** [jpaulm/drawfbp#18]
Latest version of DrawFBP not generating correct symbols for External Ports (Input, Output or OI).  

Diagram shows correct ones - will be fixed in v2.14.2

![test](https://user-images.githubusercontent.com/312871/43993810-592fc212-9d61-11e8-9c13-95990f2a02cd.png)

(Symbol for OI could use some tweaking...!)

**Comment by ERnsTL** [comment]
Using v2.14.2 the External Port I/O looks reasonably fine when connected using the tips:

![example](https://user-images.githubusercontent.com/3127919/44227544-2ce0e200-a193-11e8-8395-dd2fccaf904c.png)

**Comment by jpaulm** [comment]
Thanks, Ernst!

Closed with v2.14.2
