### ISSUE TITLE
Improve Zoom

### ISSUE THREAD

**Issue by alfa256** [jpaulm/drawfbp#3]
I'd like to get a better picture when zooming, I don't remember much about how drawing with graphics2d in java works but you can accomplish this via a transform matrix or the old trick of rendering a larger image and then resizing it to the target viewport to get some antialiasing.
It's a small detail but It'd help when doing a presentation.

**Comment by jpaulm** [comment]
Hi Alfredo,

I've added a number of rendering hints to DrawFBP, and pushed to GitHub.
The zoom looks a bit better to me, but you may want to tinker with the
rendering hints a bit yourself.  I gather that they can interact in strange
ways!

BTW I use the Graphics.scale function, which apparently maps onto a (very
simple) affine transform, so changing to a transform might not buy us
much... but I may be wrong!

Thanks for the feedback!
