### ISSUE TITLE
Keyboard shortcut documentation

### ISSUE THREAD

**Issue by alfa256** [jpaulm/drawfbp#5]
I can't find information about the keyboard shortcuts, are they available?

**Comment by jpaulm** [comment]
Hi Alfredo,

Good question!  What I have done is make the 3 functions at the top left
(File, Edit, Help) respond to the Alt key.  And I can also step through the
parts of the screen using the tab key - with a lot of help from Bob
Corrick), although it seems to take more tab steps than it should.  I also
seem to step through the icon types OK, but the enter key doesn't select
them.  I am guessing that this should be fixed...

Are there other shortcuts that would be useful?  Just let me know.

HTH

Paul

**Comment by jpaulm** [comment]
Also the alt-key combinations listed under File...

**Comment by alfa256** [comment]
I'm referring to actions in the right click menu as shortcuts, like adding/moving a bend and whatnot. Although I would prefer to move bends without any other actions other than dragging but that's for a different issue.

**Comment by jpaulm** [comment]
Oh sorry!  Look in the Help facility - there is a list of actions for Blocks, and another one for Arrows.  I think the lists are up to date...

**Comment by jpaulm** [comment]
Hello again Paul,

It's good to hear from you. I take my hat off to you for maintaining JavaFBP and DrawFBP: I'm sorry that I have not made time to test the latest versions (yet).

When we looked at keyboard operation in DrawFBP, I was thinking about convenience for opening and saving diagrams, in particular. It's likely that we'd be typing a file name or a new folder name when saving, and keyboard operation for accessing a drop-down menu and navigating the file system dialog comes naturally to me (in Windows, at least).

On the other hand, drawing only works with the pointer, and I'm very happy to select with a click and then use the keyboard for a menu (such as Alt-E for Edit then arrow keys -> description). It would be a nightmare to program TABbing between components...

I will re-test keyboard operations *in the file dialogs* in DrawFBP - my latest copy is v2.8.14 (July 14, 2014) so I will download again first - and write up the TABbing and keyboard shortcuts as I find them.

All the best to you and the family,
Bob

Date: Mon, 3 Aug 2015 10:13:40 -0400
Subject: Re: [drawfbp] Keyboard shortcut documentation (#5)
From: jpaulmorr@gmail.com
To: reply@reply.github.com
CC: sistemas.alfredo@gmail.com; bobcorrick@outlook.com

On second thoughts, the tab support is only implemented within the FileChooser - Bob, do you think we should enable this for the main DrawFBP screen as well?

On Mon, Aug 3, 2015 at 9:07 AM, Paul Morrison <jpaulmorr@gmail.com> wrote:
Hi Alfredo,

Good question!  What I have done is make the 3 functions at the top left (File, Edit, Help) respond to the Alt key.  And I can also step through the parts of the screen using the tab key - with a lot of help from Bob Corrick), although it seems to take more tab steps than it should.  I also seem to step through the icon types OK, but the enter key doesn't select them.  I am guessing that this should be fixed...

Are there other shortcuts that would be useful?  Just let me know.

HTH

Paul
 

On Sun, Aug 2, 2015 at 9:26 PM, alfa256 <notifications@github.com> wrote:
I can't find information about the keyboard shortcuts, are they available?

**Comment by jpaulm** [comment]
That would be great, Bob!  And thanks for the kind words!

I have just promoted DrawFBP 2.10.9 with a new feature which allows you to
tab through the icon types, and select one using Enter.  I am not sure why,
except the thought was triggered by something Alfredo said, and I thought I
would try it!  :-)

Working on Alfredo's Run idea - not sure if I have understood that
correctly though...

Regards,

Paul

PS What is jpaulmdrawfbp?
