### ISSUE TITLE
Attached Classes to components vanish in V2.22.1 upwards

### ISSUE THREAD

**Issue by bergm** [jpaulm/drawfbp#56]
Starting with Version V 2.22.1 and higher, attached classes (class names) suddenly vanish and keep vanished if the file has been saved in one of the newer versions.

**Comment by jpaulm** [comment]
Have pushed a commit for this problem... and I think some others.  Haven't created a new jar file as C# not tested yet...

**Comment by jpaulm** [comment]
Fixed as of v2.22.4
