### ISSUE TITLE
Wrongly generated class name for component Subin/out in C# mode 

### ISSUE THREAD

**Issue by bergm** [jpaulm/drawfbp#59]
When DrawFBP generates code for C# and the diagram is a subnet, then the class name will still contain the .class suffix (from Java I guess). E.g. ```Component("SUBIN", typeof(SubIn.class));``` instead of ```Component("SUBIN", typeof(SubIn));```

**Comment by jpaulm** [comment]
Hi @bergm , looking at my latest code, I see that I recently dropped some of the C# function...  My question is:  do you expect the Choose Component function to find C# classes?  I think I had that in earlier versions, but probably only using your local C# classes (i.e. not from a DLL)...  More research needed, I guess!

**Comment by jpaulm** [comment]
v2.22.4 promoted (not to Maven)... support for C# not in yet!

**Comment by jpaulm** [comment]
Fixed as of v2.22.4

**Comment by bergm** [comment]
> Hi @bergm , looking at my latest code, I see that I recently dropped some of the C# function... My question is: do you expect the Choose Component function to find C# classes? I think I had that in earlier versions, but probably only using your local C# classes (i.e. not from a DLL)... More research needed, I guess!

I'm not sure of what Choose Component function you are talking about. Right now I don't use some of the functionality which might really run the flow. But I attach (for code generation) the C# classes to a component. But they are at the moment just .cs files and not from a dll. But for the moment that's ok as I anyway are basically testing and evaluating some things (and FBP). So I don't have a large library of components which for a normal user would be already compiled and possibly ready to run. I copy the necessary parts of the generated code right now manually into my classes representing the flow.
