### ISSUE TITLE
Getting started simply

### ISSUE THREAD

**Issue by davidryman** [jpaulm/drawfbp#6]
I got lost in the instructions. It has to be so simple a monkey can do it.
The internal dialogue might go like this:
Flow based programming, that sounds interesting, let's have a look.
github, hmmm. let's read on.
grable, hmmmm, maven hmmmm. eclipse, hmmmmmm
crap, what else is there......

It is all about curb appeal and a welcoming front door.

This is what I did:-
Instructions for Linux Monkeys.
1. Go to http://search.maven.org
2. Search for DrawFBP.
3. Download the .tar file
4. Create FBP folder
5. Extract .tar to FBP
6. Open terminal
7. cd FBP/drawfbp-2.13.4/bin
8. ./drawfbp

Add screenshots and versions for Mac and 'doze.

**Comment by jpaulm** [comment]
Sounds good!  I assume .tar is very similar to .zip...?

Why don't I just put it in the Readme?  (I couldn't do it before because
DrawFBP wasn't on Maven!)

What's 'doze?

**Comment by davidryman** [comment]
Yes, linux monkey's distrust of Microsoft. I affectionately use M$ for Microsoft, and Doze for Windows. Don't get me wrong, I 'grew' up with Dos and Windows, but when they started lying about no dos in doze 95, I started leaving.
Need the other 2 simple instruction, i.e. M$ and Mac. 3 column table near the top.

**Comment by jpaulm** [comment]
"Need the other 2 simple instruction, i.e. M$ and Mac. 3 column table near the top. " ???
