### ISSUE TITLE
Starting drawfbp

### ISSUE THREAD

**Issue by davidryman** [jpaulm/drawfbp#7]
On start up the interface opens at a specific size every time. Give control of positioning to the system.

**Comment by jpaulm** [comment]
How 'bout if I just get it to remember the previous position and size?

**Comment by davidryman** [comment]
That would work.
Again "it is not too unusual!". I have several apps that open at specific places and have to move them every time. Sometimes the monitor is not on, sometimes they appear places the mouse won't go, i.e. outside the view port. I really don't want to be doing it all the time, it cuts down productivity.

**Comment by jpaulm** [comment]
Have promoted v2.13.5 to GitHub and Maven - give it a try?  It also puts up the lat diagram you worked on, if you exited DrawFBP without closing it.  Not sure what to do about the Splash window.
