### ISSUE TITLE
File system navigation

### ISSUE THREAD

**Issue by davidryman** [jpaulm/drawfbp#8]
When I File/Open Diagram, the file list is in a strange order, I do not know where this is set, but it cannot be changed. alphabetic order would be nice. also an option to omit hidden files. Would also save effort if it remembered where it was last time.

**Comment by jpaulm** [comment]
On Thu, Nov 10, 2016 at 2:39 PM, David Ryman <notifications@github.com>
wrote:

> When I File/Open Diagram, the file list is in a strange order,
>

I'm not seeing that - could you send me a jpg file?

> I do not know where this is set, but it cannot be changed. alphabetic
> order would be nice. also an option to omit hidden files.
>
How are hidden files marked - is this different in *nix and Windows?


> Would also save effort if it remembered where it was last time.
>

Good idea!

Regards

**Comment by davidryman** [comment]
![screenshot_2016-11-12_13-13-05](https://cloud.githubusercontent.com/assets/708895/20240269/e84cfdd0-a8d9-11e6-96a5-33cb475df126.png)

Guess what. when I tried again it worked fine. Previously the location of the JavaFBP jar file had not been set. Locate the DrawFBP Help file does however exhibit the issue.
Could be just a set up thing. Might just need a FAQ, but the order is perplexing to me. Adding that thing to click the columns to change order would give flexibility. Nix file starting with '.' are hidden.

**Comment by jpaulm** [comment]
I can suppress files starting with a period.  

However your sequencing problem doesn't show up on my system (Win 7).  I use the Collections.sort function in Java with my own comparator, to merge upper and lower case names.  I suspect that this doesn't work (consistently?) in *nix Java implementation...  I am trying out String.CASE_INSENSITIVE_ORDER as suggested in a StackOverflow post - and will make a copy available to you - probably tomorrow.

**Comment by jpaulm** [comment]
Could you take a look at the file lists in this version and let me know if there is a change?  There is a pre-release jar file in https://github.com/jpaulm/drawfbp/releases/tag/v2.13.6 .  TIA

**Comment by davidryman** [comment]
Looks similar to me. Removing the dot file may not be a good idea as they are valid in linux.

![screenshot_2016-11-16_10-58-00](https://cloud.githubusercontent.com/assets/708895/20357530/f062063e-abed-11e6-90d6-41f14fcf4635.png)

**Comment by jpaulm** [comment]
Sorry, posted my request to wrong conversation!

Hi David, could you try the sort sequence test again using

https://github.com/jpaulm/drawfbp/releases/download/v2.13.6/drawfbp-2.13.6.jar

I have dropped the sort altogether - doesn't seem to work for you, but
it may not be necessary anyway!  Thanks!

Paul

**Comment by jpaulm** [comment]
I think I restored the dot files - have they come back?  Also do you see
upper and lowercase intermingled or separate?

Thx,

Paul M.
